[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "noetic-stage"
version = "0.1.0"
description = "Generative UI Protocol (A2UI) for Noetic"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.0",
    "jsonpointer",
    "fastui",
    "noetic-knowledge"
]

[tool.setuptools.packages.find]
where = ["."]
